### PR TITLE
Added traditional chinese translation (zh-TW) 

### PR DESCRIPTION
**Pull request by janeliutw**
issue #2 
This is translation to Traditional Chinese (Taiwan)

### CODE REVIEW

**Comment by btk** [comment]
Hey @janeliutw thank you so much! 

Could you tell me how much difference is there between `zh-CN` and `zh-TW` is it noticeable or like en-US vs en-GB.

**Comment by janeliutw** [comment]
@btk yeah, the file zn-CN is using Simplify Chinese, and zh-TW is using Traditional Chinese. So a lot of the characters are different, also the use of names/terms could be different as well!

**Comment by btk** [comment]
Ok thank you, also could you tell me about `zh-Hans_HK` vs `zh-Hans_TW`

I'm also going to add your name in app as contributors!

**Comment by janeliutw** [comment]
Sure. Hongkong, Macau and Taiwan are the only places that are primarily using Traditional Chinese in the world,  we share the same characters but might use different names/ terms in some cases. So it's more like `en-US` vs `en-GB` e.g., Taxi in HongKong and Macau would be called "的士", but in Taiwan we call "計程車".
If you would like to just have a general classification for Chinese, it would be `Chinese (Traditional)` and `Chinese (Simplified)`, google translate is using this classification. But since this is a Language learning app, people might be using it when they travel to different countries, I would suggest to include different translations for Simplified (`zh-CN`), Traditional (`zh-HK`), and Traditional (`zh-TW`) as the usage of words are different.

More info if you are interested: https://en.wikipedia.org/wiki/Language_localisation
But I am also happy to answer any other questions you have!

Also, I am sorry but I just found out there was some typo in my PR, I was working late last night my eyes just got tired. I'll update it and create another PR if you don't mind.

**Comment by btk** [comment]
Thank you for the info, since this app targets kids with autism, using the exact terms are crucial, I will do as you suggest.

> Also, I am sorry but I just found out there was some typo in my PR, I was working late last night my eyes just got tired. I'll update it and create another PR if you don't mind.

Sure you can always come back and do changes and add a new PR as I try to update the app every month.

**Pull request merged**
